//
// Created by Utilisateur on 25/03/2023.
//

#ifndef MFRANCESCHI_CPPEXPERIMENTS_MYLIB_HPP
#define MFRANCESCHI_CPPEXPERIMENTS_MYLIB_HPP

int getZero();

#endif //MFRANCESCHI_CPPEXPERIMENTS_MYLIB_HPP
